# Generated by Django 3.2.6 on 2021-11-21 11:21

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='media/default.png', upload_to='profile_images/%Y/%m/%d/'),
        ),
    ]
